- name: Create nexus data dir
  file:
    path: '{{ NEXUS_DATA }}'
    state: directory

- name: Set appropriate permissions on nexus volume
  command: "chown -R 200:200 {{ NEXUS_DATA }}"
  become: yes
  become_method: sudo
- name: Run Nexus Container
  docker_container:
    name: "{{ NEXUS_HOSTNAME }}"
    image: sonatype/nexus3
    ports:
      - "{{ NEXUS_PORT }}:8081"
    volumes:
      - "{{ NEXUS_DATA }}:/nexus-data"
    networks:
      - name: appnet
