- name: Run Postgres DB Container
  docker_container:
    name: "{{ DB_CONTAINER_NAME }}"
    image: postgres:9.6-alpine
    ports:
      - "{{ DB_PORT }}:5432"
    env:
      POSTGRES_USER: "{{ POSTGRES_USER }}"
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
      POSTGRES_DB: "{{ POSTGRES_DB }}"
    volumes:
      - /var/lib/postgresql
      - /var/lib/postgresql/data
    networks:
      - name: appnet
